AWSTemplateFormatVersion: "2010-09-09"

Resources:  

  FrntPipelineRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: frontinfradeploypipelinerepo

  FrntInfraCodePipelineTrustRole:
    Description: Creating service role in IAM for AWS CodePipeline for infra deploy
    Type: AWS::IAM::Role
    Properties:
      RoleName: FrntDeployCodePipeCustRole
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Sid: 1
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            - s3:PutObject
            Effect: Allow
            Resource: '*'
          - Action:
            - codecommit:CancelUploadArchive
            - codecommit:GetBranch
            - codecommit:GetCommit
            - codecommit:GetUploadArchiveStatus
            - codecommit:UploadArchive
            Effect: Allow
            Resource: '*'
          - Action:
            - codebuild:StartBuild
            - codebuild:BatchGetBuilds
            - codebuild:StopBuild
            Effect: Allow
            Resource: '*'
          - Action:
            - codedeploy:CreateDeployment
            - codedeploy:GetApplicationRevision
            - codedeploy:GetDeployment
            - codedeploy:GetDeploymentConfig
            - codedeploy:RegisterApplicationRevision
            Effect: Allow
            Resource: '*'
          - Action:
            - 'cloudformation:*'
            Effect: Allow
            Resource: '*'
          - Action:
            - 'iam:PassRole'
            Effect: Allow
            Resource: '*'
        PolicyName: FrntDeployCodePipeCustPol

  FrntCloudFormCodePipelineTrustRole:
    Description: Creating service role in IAM for AWS CodePipeline for infra deploy
    Type: AWS::IAM::Role
    Properties:
      RoleName: FrntCFCodePipeCustRole
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Sid: 1
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - 'cloudformation:*'
            - 'iam:PassRole'
            Effect: Allow
            Resource: '*'
          - Action:
            - '*'
            Effect: Allow
            Resource: '*'
        PolicyName: FrntCFCodePipeCustPol

  FrntInfraArtifactsBucket:
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for AWS CodePipeline and CodeBuild artifacts
    Properties:
      Tags:
      - Key: Name
        Value: frntinfracodepipelineacbucketac
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket

  FrntInfraDeployPipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
    - FrntInfraCodePipelineTrustRole
    - FrntInfraArtifactsBucket
    Description: Creating a deployment pipeline for your project in AWS CodePipeline
    Properties:
      ArtifactStore:
        Location: !Ref 'FrntInfraArtifactsBucket'
        Type: S3
      Name: FrntInfraDeploypipeline
      RoleArn: !GetAtt
      - FrntInfraCodePipelineTrustRole
      - Arn
      Stages:
      - Name: Source
        Actions:
        - ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: CodeCommit
            Version: 1
          Configuration:
            BranchName: main
            PollForSourceChanges: false
            RepositoryName: !GetAtt FrntPipelineRepo.Name
          InputArtifacts: [
            ]
          Name: FrntApplicationSource
          # OutputArtifacts: [

          # ]
          OutputArtifacts:
          - Name: infrabuildsrc
          RunOrder: 1
      - Name: FrntInfraDeploy
        Actions:
        - ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            StackName: frntinfrastack
            Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
            RoleArn: !GetAtt FrntCloudFormCodePipelineTrustRole.Arn
            TemplatePath: infrabuildsrc::deployinfra.yml
          OutputArtifacts: []
          InputArtifacts:
            - Name: infrabuildsrc
          Name: FrntInfraDeploy