apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: yelp-api-autoscale
  namespace: yelpapins
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelp-review-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: v1
kind: Service
metadata:
  name: yelpa-api-service
  namespace: yelpapins
spec:
  type: NodePort
  selector:
    app: yelpapp
  ports:
    - port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: yelp-review-api-lb
  namespace: yelpapins
  labels:
    app: yelpapp
spec:
  type: LoadBalancer
  selector:
    app: yelpapp
  ports:
  - port: 80
    targetPort: 5000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-review-api
  namespace: yelpapins
  labels:
    app: yelpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelpapp
  template:
    metadata:
      labels:
        app: yelpapp
    spec:
      imagePullSecrets:
        - name: appregistrykey
      volumes:
        - name: data-files
          persistentVolumeClaim:
            claimName: data-file-vol-claim
      containers:
      - name: yelpapp
        image: <api_image_name>
        env:
            - name: INPUTBUSINESSFILE
              value: "data_files/business_data_short_1.json"
            - name: INPUTREVIEWSFILE
              value: "data_files/review_short_1.json"
            - name: INPUTMODELFILE
              value: "data_files/yelp_model_nlpV1.sav"
        volumeMounts:
          - mountPath: "/home/yelpbackendapp/data_files"
            name: data-files
        ports:
        - containerPort: 5000